services:
  - type: web
    name: qr-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
